---
fzf_version: 0.57.0
gitconfig_user_email: tgeorgomanolis@gmail.com
gitconfig_user_name: Theodoros Georgomanolis
go_checksum: f6c8a87aa03b92c4b0bf3d558e28ea03006eb29db78917daec5cfb6ec1046265
go_version: 1.22.0
hadolint_version: 2.12.0
helm_version: 3.17.0
helm_dashboard_version: 1.3.3
hvault_version: 1.10.0
k9s_version: 0.27.4
kind_version: 0.20.0
kubecolor_version: 0.0.25
kubectl_version: 1.26.0
kubectx_version: 0.9.5
kubefwd_version: 1.22.5
kubeps1_version: 0.8.0
kubeshark_version: 52.1.63
kubetail_version: 1.6.20
tf_version: 1.7.4
tgrunt_version: 0.55.10
vagrant_version: 2.4.3
yq_version: 4.30.6
allure_version: 2.22.4
